GH_OWNER = "BDePanfilis"
GH_REPO  = "Olist-DB-Private"
GH_TAG   = "latest"              
GH_ASSET = "olist.duckdb"
GH_TOKEN = "github_pat_11A5SX5YA0ENeGojNwYoj _a1ZEGXriBsKpPvQezY055Zmj6Df7ccrpRGhbvldZjiZRIFSQSFXlRImsa3e"

